name: lumody
description: "A mood tracker app."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons for IOS
  cupertino_icons: ^1.0.6

  # Service Locator
  get_it: ^7.7.0

  # BloC State Management
  bloc: ^8.1.3
  flutter_bloc: ^8.1.6

  # Being able to compare objects in Dart
  equatable: ^2.0.5

  # Fetch Data From Api
  dio: ^5.5.0

  # Supercharged brings all the comfort features from languages like Kotlin.
  supercharged: ^2.1.1

  # Allows you to display progress widgets based on percentage
  percent_indicator: ^4.2.3

  # Package for internationalization
  intl: ^0.18.1
  easy_localization: ^3.0.5

  # Packages for storing and retrieving data in key-value pairs
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0

  # Supplies the app with the directory location for storing files
  path_provider: ^2.1.4
  provider: ^6.1.2
  path: ^1.9.0

  # A flutter implementation of React hooks.
  flutter_hooks: ^0.20.5

  # A flutter plugin for adapting screen and font size.
  flutter_screenutil: ^5.9.3

  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^2.2.0

  # Allows you to easily show toast and notification messages
  toastification: ^2.1.0

  # Sharing content via the platform share UI
  # share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Defines files available to the app
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/locales/

  # Specifies fonts and their respective font weights (thickness)
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
